title: E-helaya Test site
author: GitHub User
email: ehelaya@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is test blog.

# social links
twitter_username: ehelaya
github_username:  ehelaya@gmail.com

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
